/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import ConexaoBD.ConexaoBD;
import ConexaoBD.ProdutoDAO;
import Produtos.Produto;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static jdk.nashorn.tools.ShellFunctions.input;

/**
 *
 * @author Guilherme
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    private static PrintService[] impressora;
    private Produto produto = new Produto();

    public HomeScreen() {
        initComponents();
        listaimpressora.setSelectedIndex(detectaImpressoras());
        txtpreco.setText("0,00");
        try {
            ConexaoBD con = new ConexaoBD();
            con.lerArquivo();
        } catch (Exception e) {
        }

        try {
            new File(new TestePathDaClasse().pathDaClasse(TestePathDaClasse.class) + "\\Images").mkdir();
            //JOptionPane.showMessageDialog(null, 
            //new TestePathDaClasse().pathDaClasse(TestePathDaClasse.class));

        } catch (Exception ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEAN = new javax.swing.JLabel();
        txtcodigoean = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        lblEtiquetas = new javax.swing.JLabel();
        txtqtdetiqueta = new javax.swing.JTextField();
        listaimpressora = new javax.swing.JComboBox<>();
        btnImprimir = new javax.swing.JToggleButton();
        lbldescricao = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblWhatsapp = new javax.swing.JLabel();
        txtWhatapp = new javax.swing.JTextField();
        lblInstagram = new javax.swing.JLabel();
        txtInstagram = new javax.swing.JTextField();
        lblFacebook = new javax.swing.JLabel();
        txtFacebook = new javax.swing.JTextField();
        lblImpressora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Impressão de Etiqueta");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(600, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 280));

        lblEAN.setText("Codigo de Barras");

        txtcodigoean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoeanActionPerformed(evt);
            }
        });

        lblPreco.setText("Preço");

        txtpreco.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpreco.setDragEnabled(true);
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });

        lblEtiquetas.setText("Etiquetas");

        txtqtdetiqueta.setText("2");
        txtqtdetiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdetiquetaActionPerformed(evt);
            }
        });

        listaimpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaimpressoraActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lblImagem.setPreferredSize(new java.awt.Dimension(256, 190));

        lblWhatsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawble/WhatsApp-icon.png"))); // NOI18N

        txtWhatapp.setText("(43) 99928-0526");
        txtWhatapp.setPreferredSize(new java.awt.Dimension(80, 20));
        txtWhatapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWhatappActionPerformed(evt);
            }
        });

        lblInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawble/instagram-icon-1.png"))); // NOI18N

        txtInstagram.setText("@kilax.japan");
        txtInstagram.setPreferredSize(new java.awt.Dimension(70, 20));

        lblFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawble/facebook-256.png"))); // NOI18N

        txtFacebook.setText("facebook.com/kilaxjapan");

        lblImpressora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Drawble/printer-icon--hardware-iconset--iconshow-6.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblEAN)
                    .add(lblPreco)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(lblEtiquetas)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblWhatsapp)
                            .add(lblImpressora)
                            .add(lblInstagram, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblFacebook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtpreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtqtdetiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(listaimpressora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtFacebook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtWhatapp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtInstagram, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblImagem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(41, 41, 41))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(txtcodigoean, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 5, Short.MAX_VALUE)
                                .add(lbldescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 354, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(171, 171, 171)
                                .add(btnImprimir)
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtcodigoean, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lblEAN))
                    .add(lbldescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblImagem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblPreco)
                            .add(txtpreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtqtdetiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblEtiquetas))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(listaimpressora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblImpressora))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblWhatsapp)
                            .add(txtWhatapp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(btnImprimir))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txtInstagram, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblInstagram))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblFacebook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(txtFacebook, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))))))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(593, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoeanActionPerformed
        // TODO add your handling code here:
        txtpreco.requestFocus();

        try {

            String path = new TestePathDaClasse().pathDaClasse(TestePathDaClasse.class) + "Images/" + txtcodigoean.getText() + ".jpg";
            path = path.replace('/', '\\');

            ImageIcon icon = new ImageIcon(path);
            icon.setImage(icon.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_DEFAULT));
            lblImagem.setIcon(icon);

        } catch (Exception ex) {
            Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtcodigoean.setText(txtcodigoean.getText().replace(" ", ""));
        ProdutoDAO prod = new ProdutoDAO();
        if (txtcodigoean.getText() != null || txtcodigoean.getText() != "") {
            try {

                produto = prod.getProduto(txtcodigoean.getText());
            } catch (SQLException ex) {
                Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            lbldescricao.setText(produto.getDescricao());
            txtpreco.setText(produto.getPreco().replace(".", ","));

        } else {
            lbldescricao.setText("Produto nao Encontrado");
            txtpreco.setText("0,00");
        }

    }//GEN-LAST:event_txtcodigoeanActionPerformed

    private void listaimpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaimpressoraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_listaimpressoraActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:

        produto.setFacebook(txtFacebook.getText());
        produto.setInstagram(txtInstagram.getText());
        produto.setWhatsapp(txtWhatapp.getText());

        int ind = listaimpressora.getSelectedIndex();
        PrintService sp = impressora[ind];
        if (Double.parseDouble(txtpreco.getText().replace(",", ".")) > 0) {
            produto.imprimirEtiqueta(sp, txtqtdetiqueta.getText());
            JOptionPane meuJOPane = new JOptionPane("Imprimindo....");//instanciando o JOptionPane
            final JDialog dialog = meuJOPane.createDialog(null, "Impressao de Etiquetas");//aqui uso um JDialog para manipular
            //meu JOptionPane
            dialog.setModal(true);
            //Usando o javax.swing.Timer para poder gerar um evento em um tempo determinado
            //Veja o construtor da classe Timer para mais explicações
            Timer timer = new Timer(2 * 1000, new ActionListener() {
                public void actionPerformed(ActionEvent ev) {
                    dialog.dispose();  //o evento(no caso fechar o meu JDialog)
                }
            });
            txtpreco.setText(txtpreco.getText().replace(".", ","));
            timer.start();
            dialog.setVisible(true);
            timer.stop();

        } else {
            lbldescricao.setText("Produto nao Encontrado");
            txtpreco.setText("0,00");
            String message = "Deseja inserir um PREÇO\n manualmente para imprimir?";
            String title = "Produtos nao Encontrado";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                txtpreco.requestFocus();
                txtpreco.setText("");
            } else {
                txtcodigoean.requestFocus();

            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
        txtqtdetiqueta.requestFocus();

    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtqtdetiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdetiquetaActionPerformed
        // TODO add your handling code here:
        btnImprimir.requestFocus();

    }//GEN-LAST:event_txtqtdetiquetaActionPerformed

    private void txtWhatappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWhatappActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtWhatappActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeScreen home = new HomeScreen();
                home.setVisible(true);
            }
        });
    }

    // O metodo verifica se existe impressora conectada e a  
    // define como padrao.  
    public int detectaImpressoras() {
        PrintService service = PrintServiceLookup.lookupDefaultPrintService();
        int ind = 0;
        try {

            DocFlavor df = DocFlavor.SERVICE_FORMATTED.PRINTABLE;
            PrintService[] ps = PrintServiceLookup.lookupPrintServices(df, null);
            impressora = ps;
            for (int i = 0; i < impressora.length; i++) {
                if (service.getName().equalsIgnoreCase(impressora[i].getName())) {
                    ind = i;
                }
                listaimpressora.addItem(impressora[i].getName());
            }

        } catch (Exception e) {

            e.printStackTrace();

        }
        return ind;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEAN;
    private javax.swing.JLabel lblEtiquetas;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImpressora;
    private javax.swing.JLabel lblInstagram;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblWhatsapp;
    private javax.swing.JLabel lbldescricao;
    private javax.swing.JComboBox<String> listaimpressora;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtInstagram;
    private javax.swing.JTextField txtWhatapp;
    private javax.swing.JTextField txtcodigoean;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtqtdetiqueta;
    // End of variables declaration//GEN-END:variables
}
